"""
    Clock Agent
    
    *not used at the moment*
    Timebase generated by main GTK window

    @author: Jean-Lou Dupont
    @date: 17 May 2010
"""
from threading import Event

from app.system.tbase import AgentThreadedBase

INTERVAL_MINUTES=30


class ClockAgent(AgentThreadedBase):
    """
    Clock Agent
    
    Time-base
    """
    
    def __init__(self, interval):
        """
        @param interval: interval in seconds
        """
        AgentThreadedBase.__init__(self)

        self.interval = interval
        self.count = 0
        self.finished = Event()
        
    def run(self):

        self.tick()
        
        while True:
            self.finished.wait(self.interval)
            self.tick()
            self.count += 1
            
    def tick(self):
        """
        Default 'tick' method
        """
        print "tick, count: " + str(self.count)
        self.pub("tick", self.count)
    
    
#_clock=ClockAgent(INTERVAL_MINUTES*60)

_clock=ClockAgent(2) 
_clock.start()
